[package]
name = "edcopo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
clap = "4.5.21"
dotenv = "0.15.0"
sea-orm = "1.1.1"
tokio = { version = "1.41.1", features = ["full"] }
tokio-postgres = "0.7.12"
